"""empty message

Revision ID: 0bb895aded90
Revises: 8f4fc9f3e532
Create Date: 2019-10-10 01:43:56.834643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bb895aded90'
down_revision = '8f4fc9f3e532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpool', sa.Column('carpool_type', sa.String(length=16), nullable=True))
    op.add_column('carpool', sa.Column('days', sa.String(length=32), nullable=True))
    op.add_column('carpool', sa.Column('start', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carpool', 'start')
    op.drop_column('carpool', 'days')
    op.drop_column('carpool', 'carpool_type')
    # ### end Alembic commands ###
