"""empty message

Revision ID: 8f4fc9f3e532
Revises: fc112d31bfac
Create Date: 2019-09-18 02:55:57.022133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f4fc9f3e532'
down_revision = 'fc112d31bfac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_carpool_name', table_name='carpool')
    op.create_index(op.f('ix_carpool_name'), 'carpool', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carpool_name'), table_name='carpool')
    op.create_index('ix_carpool_name', 'carpool', ['name'], unique=1)
    # ### end Alembic commands ###
