"""empty message

Revision ID: fc112d31bfac
Revises: 
Create Date: 2019-09-18 01:45:52.606785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc112d31bfac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    op.create_table('carpool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('summary', sa.String(length=128), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('from_location', sa.String(length=32), nullable=True),
    sa.Column('to_location', sa.String(length=32), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carpool_name'), 'carpool', ['name'], unique=True)
    op.create_index(op.f('ix_carpool_time_created'), 'carpool', ['time_created'], unique=False)
    op.create_table('passengers',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('carpool_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carpool_id'], ['carpool.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passengers')
    op.drop_index(op.f('ix_carpool_time_created'), table_name='carpool')
    op.drop_index(op.f('ix_carpool_name'), table_name='carpool')
    op.drop_table('carpool')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
